### ISSUE TITLE
How to distinguish "features" from "fields"

### ISSUE THREAD

**Issue by GentaK2018** [mascaroa/pyffm#1]
@mascaroa 
Helle,
I'm a beginner of FFM and starting to use your pyffm library.
I can't understand how to read a dataframe with both "fields" and "features" for a ffm model.
I guess your example as below in pyffm.py is for either "fields" or "features.
```
click    field1    field2  ...  fieldN
0       163825     2112          3.57
1       116178     3104          3.14
```
Could you please tell me how to read a dataframe or other format with both "field" and "features" for a ffm model.
Best regards

**Comment by mascaroa** [comment]
Hi @GentaK2018,

Good question! Formatting and encoding data properly can be quite tricky for FFM, but it also often sounds more complicated than it is. In the example dataframe, "field2", "field2", etc. are of course the "fields" while the "features" are simply the data in the columns (163825, 116178, ...). 

The fields are encoded to integer values, so a mapping is generated like:
"field1" -> 0
"field2" -> 1
etc., so that they can be mapped to a specific row in the latent vector matrix.

Categorical features (these can be strings or integers) are mapped the same way:
"163825" -> 0
"116178" -> 1
"2112" -> 2
etc. (or in the case of strings, it would map something like "feature1" -> 0, etc....)

Categorical features will always have a _value_ of 1 (0 meaning the feature is *not* present).

For numerical features (_any column of floats is handled as numerical_) the value is simply the value in the raw data
e.g.: 3.57, 3.14

Think of every entry in the dataframe as a tuple like: (field, feature, value)
For example, the first row can be written:
("field1", "163825", 1), ("field2", "2112", 1), ("fieldN", "fieldNfeature", 3.57)

So, to answer your question, you don't have to do anything extra to read a dataframe with fields and features as it's all handled internally! 

Let me know if you have any other questions, also I'll be adding more documentation on all of the features and some of the quirks of FFM data handling soon.

Cheers,
Aaron

**Comment by GentaK2018** [comment]
@mascaroa 
Thank you for your replying.
Now, I can understand the tricky data structure in FFM, and I have another question for numerical features.
It's acceptable for me to binarize categorical features like "one-hot encoding" and format them to [field, feature, value]. 
For numerical features, I think "feature" must be same, but actually it's not.
In the example above and your implementation, "feature" is different in the formatted data structure between row1 and row2 as below.
* row1 -> ("fieldN", "fieldNfeature**1**", 3.57)
* row2 -> ("fieldN", "fieldNfeature**2**", 3.14)

Can we get reasonable model for the "fieldN"?

**Comment by mascaroa** [comment]
Hi @GentaK2018,

For FFM you don't need to use one-hot encoding, simple label encoding is the best way to handle the data (i.e. mapping categorical features to integers, like: "feature1" -> 0, "feature2" -> 1, etc...). This part is taken care of in the pyffm file, have a look at the data formatting functions around line 247. 

For numerical fields, the "features" should all be the same in most cases as they're essentially just dummy variables, but there may be a use case where you want different features with different values in the same field, although I haven't come across this myself yet. I think the best way to handle that is to create new fields with different values instead of features with different values in the same field, e.g. instead of:

- row1 -> ("fieldN", "fieldNfeature1", 3.57)
- row2 -> ("fieldN", "fieldNfeature2", 3.14)

you can do:

- row1 -> ("fieldN", "fieldNfeature", 3.57)
- row2 -> ("fieldN2", "fieldN2feature", 3.14)

If you're working with dataframes you can either leave the fields as NaNs or set them to 0. A value of 0 will have no effect on the model because of the way the model values are computed (w_(feat1, field2) . w_(feat2, field1) * val1 * val2).

Let me know if this helps at all or if you have any other questions.

Cheers!
Aaron
